# Generated by Django 5.1.3 on 2025-02-03 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_parts', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='product_image1',
        ),
        migrations.RemoveField(
            model_name='products',
            name='product_image2',
        ),
        migrations.AddField(
            model_name='products',
            name='product_image2_url',
            field=models.ImageField(default='default_image.png', max_length=200, upload_to=''),
        ),
        migrations.AddField(
            model_name='products',
            name='product_image_url',
            field=models.URLField(default='default_image.png'),
        ),
    ]
