# Generated by Django 5.1.3 on 2025-02-03 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_parts', '0003_remove_products_product_image1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_image2_url',
            field=models.URLField(default='default_image.png'),
        ),
    ]
