# Generated by Django 5.1.3 on 2025-02-03 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garage_services',
            name='garage_image',
        ),
        migrations.AddField(
            model_name='garage_services',
            name='garage_image_url',
            field=models.URLField(default='default_image.png'),
        ),
    ]
