# Generated by Django 5.1.3 on 2025-02-03 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='car_image',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='car_image2',
        ),
        migrations.AddField(
            model_name='cars',
            name='car_image2_url',
            field=models.CharField(default='default_image.png', max_length=255),
        ),
        migrations.AddField(
            model_name='cars',
            name='car_image_url',
            field=models.URLField(default='default_image.png'),
        ),
    ]
